##############################################################################
#  04_metrics.R
#  Compute portfolio performance metrics from rolling window results
#
#  Input  : results/rolling_results.rds  (produced by 03_rolling_window.R)
#
#  Metrics per method:
#    Ann. Return   — mean monthly H-L × 12 × 100  (percent)
#    Sharpe        — annualised (mean/sd × sqrt(12))
#    t-stat        — mean H-L / (sd / sqrt(n))
#    Win Rate      — % months with positive H-L
#    Max Drawdown  — worst cumulative peak-to-trough (percent)
#    Avg K         — mean detected groups (AFEM only)
#
#  Outputs:
#    results/perf_table.csv
#    results/perf_table.tex   (booktabs, ICML-ready)
##############################################################################

suppressPackageStartupMessages({
  library(dplyr)
})

dir.create("results", showWarnings = FALSE)

## ── load ──────────────────────────────────────────────────────────────────────
ret_df <- tryCatch(
  readRDS("results/rolling_results.rds"),
  error = function(e) stop("[metrics] run 03_rolling_window.R first: ", e$message)
)

## ── metric helpers ────────────────────────────────────────────────────────────
annualised_sharpe <- function(x) {
  x <- x[is.finite(x)]
  if (length(x) < 3) return(NA_real_)
  (mean(x) / sd(x)) * sqrt(12)
}

max_drawdown <- function(x) {
  x   <- x[is.finite(x)]
  if (length(x) == 0) return(NA_real_)
  cum <- cumprod(1 + x)
  min((cum - cummax(cum)) / cummax(cum)) * 100   # return as percent
}

## ── method display order ──────────────────────────────────────────────────────
# Matches the underscore names used in 03_rolling_window.R
METHOD_ORDER  <- c("Homogeneous_FM", "Static_Hetero", "SplineKM", "AFEM")
# Pretty labels for the LaTeX table
METHOD_LABELS <- c("Homogeneous_FM" = "Homogeneous FM",
                   "Static_Hetero"  = "Static Hetero",
                   "SplineKM"       = "SplineKM",
                   "AFEM"           = "AFEM")

## ── compute summary ───────────────────────────────────────────────────────────
perf <- ret_df %>%
  group_by(method) %>%
  summarise(
    N_months     = n(),
    mean_ret_mo  = mean(hl_ret, na.rm = TRUE),
    mean_ret_ann = mean_ret_mo * 12 * 100,
    sd_ret_mo    = sd(hl_ret,   na.rm = TRUE),
    sharpe_ann   = annualised_sharpe(hl_ret),
    t_stat       = mean(hl_ret, na.rm = TRUE) /
      (sd(hl_ret, na.rm = TRUE) / sqrt(n())),
    win_rate     = mean(hl_ret > 0, na.rm = TRUE) * 100,
    max_dd       = max_drawdown(hl_ret),
    mean_K       = mean(K_used, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  mutate(method = factor(method, levels = METHOD_ORDER)) %>%
  arrange(method)

print(as.data.frame(perf))
write.csv(perf, "results/perf_table.csv", row.names = FALSE)
message("[metrics] saved results/perf_table.csv")

## ── LaTeX table (booktabs) ────────────────────────────────────────────────────
best_bl_sharpe <- max(perf$sharpe_ann[perf$method != "AFEM"], na.rm = TRUE)

fmt_num <- function(val, fmt, is_afem, is_best) {
  s <- sprintf(fmt, val)
  if (is_afem) return(sprintf("\\textbf{%s}", s))
  if (is_best) return(sprintf("\\underline{%s}", s))
  s
}

tex <- c(
  "% Auto-generated by 04_metrics.R",
  "\\begin{table}[t]",
  "\\centering",
  "\\caption{Out-of-sample H-L portfolio performance (equal-weighted, annualised).}",
  "\\label{tab:empirical_perf}",
  "\\begin{tabular}{lrrrrrr}",
  "\\toprule",
  paste("Method",
        "Ann.\\ Return (\\%)",
        "Sharpe",
        "$t$-stat",
        "Win Rate (\\%)",
        "Max DD (\\%)",
        "$\\hat{K}$",
        sep = " & "),
  "\\\\ \\midrule"
)

for (i in seq_len(nrow(perf))) {
  m       <- as.character(perf$method[i])
  is_afem <- m == "AFEM"
  is_best <- !is_afem && !is.na(perf$sharpe_ann[i]) &&
    abs(perf$sharpe_ann[i] - best_bl_sharpe) < 1e-9

  ret_s <- fmt_num(perf$mean_ret_ann[i], "%.2f\\%%", is_afem, is_best)
  sr_s  <- fmt_num(perf$sharpe_ann[i],  "%.2f",     is_afem, is_best)
  ts_s  <- fmt_num(perf$t_stat[i],      "%.2f",     is_afem, is_best)
  wr_s  <- fmt_num(perf$win_rate[i],    "%.1f\\%%", is_afem, is_best)
  dd_s  <- fmt_num(perf$max_dd[i],      "%.2f",     is_afem, is_best)
  k_val <- if (!is.na(perf$mean_K[i])) sprintf("%.1f", perf$mean_K[i]) else "1"
  k_s   <- if (is_afem) sprintf("\\textbf{%s}", k_val) else k_s <- k_val

  label <- METHOD_LABELS[m]
  tex   <- c(tex, sprintf("%s & %s & %s & %s & %s & %s & %s \\\\",
                          label, ret_s, sr_s, ts_s, wr_s, dd_s, k_s))
}

tex <- c(tex,
         "\\bottomrule",
         "\\multicolumn{7}{l}{\\small Best baseline \\underline{underlined}; AFEM \\textbf{bold}. $\\hat{K}$ = avg.\\ detected groups.}\\\\",
         "\\end{tabular}",
         "\\end{table}")

writeLines(tex, "results/perf_table.tex")
message("[metrics] saved results/perf_table.tex")
cat(paste(tex, collapse = "\n"), "\n")
